### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by sepiariver** [ryancrideout/Ryan_Professional_Development#9]
Follow on from #2

**Comment by ryancrideout** [comment]
Criteria for success:

- Someone can refer to STEP-BY-STEP instructions to operate the code. This includes all of the requirements, and make sure that people are on the right system, right requirements, etc. This is looking like I might need to use pipenv install.
- And of course, unit tests!

**Comment by ryancrideout** [comment]
I think this is done, so I'm going to close this for now. We can revisit this later, but I've added a whole bunch of unit tests as well as instructions on how to run the code.

Of course, you can be the judge if I actually did that haha.
